# version: '3.8'
services:

  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:cached
    environment:
      - ALLOWED_HOSTS=mining.utrizd.com,localhost

  celery:
    command: celery -A cashcrm_project worker -l info
    volumes:
      - .:/code:cached
