# version: '3.8'
services:

  db:
    image: postgres:15
    env_file: .env.dev
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - nginx-proxy


  redis:
    image: redis:6
    restart: always
    networks:
      - nginx-proxy

  web:
    build: .
    container_name: maemohp9-web-dev
    # ENTRYPOINT จะทำ migrations + collectstatic ให้ก่อน แล้วรัน CMD ต่อไปนี้ (runserver)
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env.dev
    # ไม่ mount staticfiles ทับ
    volumes:
      - .:/app:rw
      - ./static:/app/static    # สำหรับไฟล์ static แบบดิบ (เช่น CSS/JS ที่แก้ระหว่าง dev)

    ports:
      - "8000:8000"

    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      

    depends_on:
      db:
         condition: service_healthy
      redis:
          condition: service_started
    restart: always
    networks:
      - nginx-proxy

  celery:
    build: .
    container_name: maemohp9-celery-dev
    command: celery -A cashcrm_project worker -l info
    env_file: .env.dev
    
    volumes:
      - .:/app:rw

    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      redis:
          condition: service_started
      db:
          condition: service_healthy
    restart: always
    networks:
      - nginx-proxy


  celery-beat:
    build: .
    container_name: maemohp9-celery-beat-dev
    command: celery -A cashcrm_project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file: .env.dev
    volumes:
      - .:/app:rw

    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:            # ถ้าไม่มี healthcheck จะถือว่ามี condition=service_started
        condition: service_started
    restart: always
    networks:
      - nginx-proxy

  

volumes:
  postgres_data:

networks:
  nginx-proxy:
    external: true