# version: '3.8'
services:

  db:
    image: postgres:15
    env_file: .env.prod
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:       ${POSTGRES_DB}
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - nginx-proxy


  redis:
    image: redis:6
    restart: always
    networks:
      - nginx-proxy

  web:
    build: .
    image: maemohp9-web:prod
    command:
      - bash
      - -c
      - |
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn cashcrm_project.wsgi:application --workers 2 --bind 0.0.0.0:8000
    env_file: .env.prod
    labels:
      - "VIRTUAL_HOST=${VIRTUAL_HOST}"
      - "LETSENCRYPT_HOST=${LETSENCRYPT_HOST}"
      - "LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"

    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - VIRTUAL_PORT=8000
      
    depends_on:
      db:
          condition: service_healthy
      redis:
          condition: service_started
    restart: always
    networks:
      - nginx-proxy

  celery:
    build: .
    image: maemohp9-celery:prod
    command: >
      bash -c "
        celery -A cashcrm_project worker -l info
      "
    # command: celery -A cashcrm_project worker -l info
    env_file: .env.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      redis:
          condition: service_started
      db:
          condition: service_healthy
      
    restart: always
    networks:
      - nginx-proxy


  celery-beat:
    build: .
    image: maemohp9-celery-beat:prod
    command: >
      bash -c "
        python manage.py migrate --noinput &&
        celery -A cashcrm_project beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    env_file: .env.prod
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      redis:            # ถ้าไม่มี healthcheck จะถือว่ามี condition=service_started
        condition: service_started
    restart: always
    networks:
      - nginx-proxy

  

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  nginx-proxy:
    external: true