# Generated by Django 4.2.21 on 2025-08-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemainingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True)),
                ('budget_year', models.IntegerField()),
                ('budget_code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('actual_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('usage_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('budget_owner', models.CharField(blank=True, default='', max_length=100)),
                ('budget_group', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot_at'], name='analytics_r_snapsho_b26d06_idx'), models.Index(fields=['budget_year'], name='analytics_r_budget__afa5f8_idx'), models.Index(fields=['usage_pct'], name='analytics_r_usage_p_56860f_idx'), models.Index(fields=['budget_owner'], name='analytics_r_budget__6acedb_idx'), models.Index(fields=['budget_group'], name='analytics_r_budget__5dbf50_idx')],
            },
        ),
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_year', models.IntegerField()),
                ('budget_code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('budget_group', models.CharField(blank=True, default='', max_length=100)),
                ('budget_subgroup', models.CharField(blank=True, default='', max_length=100)),
                ('budget_type', models.CharField(blank=True, default='', max_length=50)),
                ('budget_owner', models.CharField(blank=True, default='', max_length=100)),
                ('dept', models.CharField(blank=True, default='', max_length=100)),
                ('ro_order', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['budget_year', 'budget_code'], name='analytics_b_budget__83c558_idx')],
                'unique_together': {('budget_year', 'budget_code')},
            },
        ),
        migrations.CreateModel(
            name='BudgetActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_date', models.DateField()),
                ('budget_code', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('source', models.CharField(max_length=20)),
                ('load_batch_id', models.CharField(max_length=40)),
            ],
            options={
                'indexes': [models.Index(fields=['doc_date'], name='analytics_b_doc_dat_00bd4f_idx'), models.Index(fields=['budget_code'], name='analytics_b_budget__6bd2d6_idx')],
            },
        ),
    ]
