# Generated by Django 4.2.21 on 2025-08-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetactual',
            name='event_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetactual',
            name='seq_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetactual',
            name='source_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='budgetactual',
            index=models.Index(fields=['event_ts'], name='analytics_b_event_t_c19b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetactual',
            index=models.Index(fields=['source', 'doc_date'], name='analytics_b_source_72cbf2_idx'),
        ),
    ]
