# Generated by Django 4.2.21 on 2025-08-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_budgetactual_event_ts_budgetactual_seq_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoIndex',
            fields=[
                ('ro_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('budget_code', models.CharField(db_index=True, max_length=50)),
                ('budget_year', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
        ),
        migrations.AddIndex(
            model_name='budgetactual',
            index=models.Index(fields=['source_ref'], name='analytics_b_source__d2437f_idx'),
        ),
        migrations.AddIndex(
            model_name='roindex',
            index=models.Index(fields=['budget_code', 'budget_year'], name='analytics_r_budget__28ed2d_idx'),
        ),
        migrations.AddIndex(
            model_name='roindex',
            index=models.Index(fields=['created_at'], name='analytics_r_created_6a6c1a_idx'),
        ),
    ]
