# Generated by Django 4.2.21 on 2025-06-25 07:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('year', models.PositiveSmallIntegerField(choices=[(2566, 'ปี 2566'), (2567, 'ปี 2567')])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100, unique=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=16)),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Subcontractor', 'Subcontractor'), ('Fuel Supplier', 'Fuel Supplier'), ('Spare Parts', 'Spare Parts'), ('General Service', 'General Service'), ('Insurance', 'Insurance')], max_length=30)),
                ('payment_terms', models.CharField(blank=True, max_length=20)),
                ('tax_withholding_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='SiteOperationExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expense_category', models.CharField(choices=[('Salary & Wage', 'Salary & Wage'), ('Fuel', 'Fuel'), ('Subcontractor', 'Subcontractor'), ('Blasting Mat.', 'Blasting Material'), ('Lubricant', 'Lubricant'), ('Spare part', 'Spare part'), ('Main Equipment Overhaul', 'Main Equipment Overhaul'), ('Service & General', 'Service & General'), ('Insurance', 'Insurance'), ('Excess Electricity', 'Excess Electricity'), ('Withholding Tax', 'Withholding Tax'), ('Breakdown Repair', 'Breakdown Repair'), ('Conveyor Belt Extend', 'Conveyor Belt Extend')], max_length=30)),
                ('pr_po_reference', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_withheld', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('Pending_AP', 'Pending AP'), ('AP_Invoiced', 'AP Invoiced'), ('Paid', 'Paid')], default='Pending_AP', max_length=20)),
                ('ap_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_expenses', to='payables.accountspayable')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_expenses', to='payables.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='payables.vendor'),
        ),
    ]
