# Generated by Django 4.2.21 on 2025-06-25 07:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenue', '0001_initial'),
        ('payables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='committee_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LCRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('lc_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('lc_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending_ProfReview', 'Pending Professor Review'), ('Prof_Approved', 'Professor Approved'), ('LC_Created', 'LC Created'), ('Swift_Sent', 'Swift Sent'), ('TR_Converted', 'TR Converted'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Pending_ProfReview', max_length=20)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='อธิบายเหตุผลโดยสังเขปของการขอจ่ายเงิน')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('scheduled_date', models.CharField(blank=True, help_text="รอบการรวม เช่น '5','15','25' หรือเว้นว่างให้กำหนดเอง", max_length=2)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Committee_Review', 'Committee Review'), ('CFO_Review', 'CFO Review'), ('PD_Approval', 'PD Approval'), ('Executed', 'Executed'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymentrequests_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('payment_type', models.CharField(choices=[('LC', 'LC'), ('PN', 'PN'), ('Cash', 'Cash'), ('ITDLoan', 'ITDLoan'), ('SupplierCredit', 'SupplierCredit')], max_length=20)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('chosen', models.BooleanField(default=False)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cashflow.paymentrequest')),
                ('related_ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payables.accountspayable')),
                ('related_expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payables.siteoperationexpense')),
                ('related_lcrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashflow.lcrequest')),
                ('related_suppliercredit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payables.suppliercredit')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_number', models.CharField(blank=True, max_length=100)),
                ('tr_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Repaid', 'Repaid'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('lc_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tr_request', to='cashflow.lcrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SwiftMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('lc_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swift_messages', to='cashflow.lcrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PostFinanceFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=16)),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postfinance_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PNTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('ticket_number', models.CharField(blank=True, max_length=100)),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Executed', 'Executed')], default='Pending', max_length=20)),
                ('payment_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pn_ticket', to='cashflow.paymentrequestitem')),
            ],
        ),
        migrations.CreateModel(
            name='PNLoanUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('approved_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('bank_interest_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('repayment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('repayment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Partial_Repaid', 'Partial Repaid'), ('Repaid', 'Repaid')], default='Active', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pn_loans', to='cashflow.postfinancefacility')),
                ('revenue_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pn_loans', to='revenue.revenuejob')),
            ],
        ),
        migrations.AddField(
            model_name='lcrequest',
            name='payment_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lc_request', to='cashflow.paymentrequestitem'),
        ),
        migrations.CreateModel(
            name='ITDLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(default='ITD CEM Loan', max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('300000000.00'), max_digits=16)),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itdloan_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('Revenue_Paid', 'Revenue Paid'), ('Receive_PNLoan', 'Receive PNLoan'), ('Receive_TradeFinance', 'Receive TradeFinance'), ('Receive_BankLoan', 'Receive BankLoan'), ('Receive_ITDLoan', 'Receive ITDLoan'), ('PNLoan_Repayment', 'PNLoan Repayment'), ('TradeFinance_Repayment', 'TradeFinance Repayment'), ('BankLoan_Repayment', 'BankLoan Repayment'), ('LC_Payment', 'LC Payment'), ('TR_Payment', 'TR Payment'), ('PNTicket_Issue', 'PNTicket Issue'), ('Cash_Payment', 'Cash Payment'), ('LC_Fee', 'LC Fee'), ('ITDLoan_Usage', 'ITDLoan Usage'), ('Interest_Fee', 'Interest Fee'), ('Supplier_Credit_Usage', 'Supplier Credit Usage')], max_length=30)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_inflow', models.BooleanField()),
                ('description', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='cashflow.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('check_number', models.CharField(blank=True, max_length=100)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Rejected', 'Rejected'), ('Cleared', 'Cleared')], default='Pending', max_length=20)),
                ('payment_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment', to='cashflow.paymentrequestitem')),
            ],
        ),
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_month', models.DateField()),
                ('projected_cash_inflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('projected_cash_outflow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('net_cash_flow', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('scenario', models.CharField(choices=[('Base', 'Base Case'), ('Worst', 'Worst Case'), ('Best', 'Best Case')], default='Base', max_length=10)),
                ('assumptions', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('forecast_month', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_on', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cashflow.paymentrequestitem')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='cashflow.committeemember')),
            ],
            options={
                'unique_together': {('member', 'item')},
            },
        ),
    ]
