# Generated by Django 4.2.21 on 2025-06-25 07:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('job_code', models.CharField(choices=[('Job1', 'Excavation and Removal of Overburden'), ('Job2', 'Extraction of Lignite'), ('Job3', 'Conveying of Overburden'), ('Job4', 'ค่า k'), ('DieselSale', 'รายได้จากการขายน้ำมันดีเซล'), ('Other', 'รายได้อื่นๆ')], max_length=20)),
                ('description', models.CharField(blank=True, help_text="อธิบายงานหรือผลงาน (เช่น 'งานเดือน ม.ค. 2568')", max_length=200)),
                ('volume', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('income_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Requested_PN', 'Requested PN'), ('Invoiced', 'Invoiced'), ('Paid', 'Paid')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partially Paid'), ('Paid', 'Paid')], default='Unpaid', max_length=20)),
                ('revenue_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_records', to='revenue.revenuejob')),
            ],
        ),
    ]
